vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "traffic"
vim.o.termguicolors = true

local c = {
  bg        = "#272c30",
  fg        = "#cfb9a8",
  black     = "#282d31",
  red       = "#934e46",
  green     = "#637268",
  yellow    = "#c79e84",
  blue      = "#515e67",
  magenta   = "#715f5e",
  cyan      = "#5c6f7d",
  white     = "#cfb9a8",
  br_black  = "#4e575e",
  br_green  = "#637270",
  br_white  = "#ddcec2",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ── Base UI ──────────────────────────────────────────────────────────────────
hi("Normal",          { fg = c.fg,       bg = c.bg })
hi("NormalNC",        { fg = c.fg,       bg = c.bg })
hi("NormalFloat",     { fg = c.fg,       bg = c.black })
hi("FloatBorder",     { fg = c.br_black, bg = c.black })
hi("EndOfBuffer",     { fg = c.black })
hi("ColorColumn",     { bg = c.black })
hi("Conceal",         { fg = c.br_black })
hi("Cursor",          { fg = c.bg,       bg = c.fg })
hi("CursorIM",        { fg = c.bg,       bg = c.fg })
hi("CursorLine",      { bg = c.black })
hi("CursorColumn",    { bg = c.black })
hi("Directory",       { fg = c.cyan })
hi("DiffAdd",         { fg = c.green })
hi("DiffChange",      { fg = c.yellow })
hi("DiffDelete",      { fg = c.red })
hi("DiffText",        { fg = c.yellow,   bold = true })
hi("ErrorMsg",        { fg = c.red })
hi("VertSplit",        { fg = c.bg, bg = c.bg })
hi("WinSeparator",    { fg = c.bg, bg = c.bg })
hi("Folded",          { fg = c.br_black, bg = c.black })
hi("FoldColumn",      { fg = c.br_black, bg = c.bg })
hi("SignColumn",      { fg = c.br_black, bg = c.bg })
hi("IncSearch",       { fg = c.bg,       bg = c.br_white })
hi("Substitute",      { fg = c.bg,       bg = c.yellow })
hi("LineNr",          { fg = c.br_black })
hi("CursorLineNr",    { fg = c.yellow,   bold = true })
hi("MatchParen",      { fg = c.yellow,   bold = true })
hi("ModeMsg",         { fg = c.fg })
hi("MsgArea",         { fg = c.fg })
hi("MoreMsg",         { fg = c.green })
hi("NonText",         { fg = c.br_black })
hi("Pmenu",           { fg = c.fg,       bg = c.black })
hi("PmenuSel",        { fg = c.bg,       bg = c.yellow })
hi("PmenuSbar",       { bg = c.black })
hi("PmenuThumb",      { bg = c.br_black })
hi("Question",        { fg = c.green })
hi("QuickFixLine",    { fg = c.bg,       bg = c.yellow })
hi("Search",          { fg = c.bg,       bg = c.yellow })
hi("SpecialKey",      { fg = c.br_black })
hi("SpellBad",        { sp = c.red,      undercurl = true })
hi("SpellCap",        { sp = c.yellow,   undercurl = true })
hi("SpellLocal",      { sp = c.cyan,     undercurl = true })
hi("SpellRare",       { sp = c.magenta,  undercurl = true })
hi("StatusLine",      { fg = c.fg,       bg = c.black })
hi("StatusLineNC",    { fg = c.br_black, bg = c.black })
hi("TabLine",         { fg = c.br_black, bg = c.black })
hi("TabLineFill",     { bg = c.black })
hi("TabLineSel",      { fg = c.fg,       bg = c.bg,     bold = true })
hi("Title",           { fg = c.fg, bold = true })
hi("Visual",          { fg = c.fg, bg = "#1e2226" })
hi("VisualNOS",       { fg = c.fg, bg = "#1e2226" })
hi("WarningMsg",      { fg = c.yellow })
hi("WildMenu",        { fg = c.bg,       bg = c.yellow })
hi("WinBar",          { fg = c.fg,       bg = c.bg })
hi("WinBarNC",        { fg = c.br_black, bg = c.bg })

-- ── Syntax ───────────────────────────────────────────────────────────────────
hi("Comment",        { fg = c.green,    italic = true })
hi("Constant",       { fg = c.yellow })
hi("String",         { fg = c.yellow })
hi("Character",      { fg = c.yellow })
hi("Number",         { fg = c.yellow })
hi("Boolean",        { fg = c.red })
hi("Float",          { fg = c.yellow })
hi("Identifier",     { fg = c.fg })
hi("Function",       { fg = c.fg })
hi("Statement",      { fg = c.red })
hi("Conditional",    { fg = c.red })
hi("Repeat",         { fg = c.red })
hi("Label",          { fg = c.red })
hi("Operator",       { fg = c.br_black })
hi("Keyword",        { fg = c.red })
hi("Exception",      { fg = c.red })
hi("PreProc",        { fg = c.magenta })
hi("Include",        { fg = c.magenta })
hi("Define",         { fg = c.magenta })
hi("Macro",          { fg = c.magenta })
hi("PreCondit",      { fg = c.magenta })
hi("Type",           { fg = c.cyan })
hi("StorageClass",   { fg = c.cyan })
hi("Structure",      { fg = c.cyan })
hi("Typedef",        { fg = c.cyan })
hi("Special",        { fg = c.cyan })
hi("SpecialChar",    { fg = c.yellow })
hi("Tag",            { fg = c.cyan })
hi("Delimiter",      { fg = c.br_black })
hi("SpecialComment", { fg = c.green,    italic = true })
hi("Debug",          { fg = c.red })
hi("Underlined",     { underline = true })
hi("Error",          { fg = c.red,      bold = true })
hi("Todo",           { fg = c.yellow,   bold = true })

-- ── Treesitter ───────────────────────────────────────────────────────────────
hi("@comment",              { link = "Comment" })
hi("@comment.documentation",{ fg = c.green })
hi("@keyword",              { link = "Keyword" })
hi("@keyword.function",     { fg = c.red })
hi("@keyword.operator",     { fg = c.br_black })
hi("@keyword.return",       { fg = c.red })
hi("@keyword.import",       { fg = c.magenta })
hi("@conditional",          { link = "Conditional" })
hi("@repeat",               { link = "Repeat" })
hi("@exception",            { link = "Exception" })
hi("@operator",             { link = "Operator" })
hi("@string",               { link = "String" })
hi("@string.escape",        { fg = c.cyan })
hi("@string.regex",         { fg = c.cyan })
hi("@string.special",       { fg = c.cyan })
hi("@character",            { link = "Character" })
hi("@number",               { link = "Number" })
hi("@float",                { link = "Float" })
hi("@boolean",              { link = "Boolean" })
hi("@constant",             { link = "Constant" })
hi("@constant.builtin",     { fg = c.yellow,  italic = true })
hi("@constant.macro",       { fg = c.magenta })
hi("@function",             { link = "Function" })
hi("@function.builtin",     { fg = c.fg, italic = true })
hi("@function.macro",       { fg = c.magenta })
hi("@function.call",        { fg = c.fg })
hi("@method",               { fg = c.fg })
hi("@method.call",          { fg = c.fg })
hi("@constructor",          { fg = c.cyan })
hi("@parameter",            { fg = c.fg })
hi("@variable",             { fg = c.fg })
hi("@variable.builtin",     { fg = c.red,     italic = true })
hi("@field",                { fg = c.fg })
hi("@property",             { fg = c.fg })
hi("@attribute",            { fg = c.yellow })
hi("@type",                 { link = "Type" })
hi("@type.builtin",         { fg = c.cyan,    italic = true })
hi("@type.definition",      { fg = c.cyan })
hi("@namespace",            { fg = c.magenta })
hi("@include",              { link = "Include" })
hi("@preproc",              { link = "PreProc" })
hi("@define",               { link = "Define" })
hi("@label",                { link = "Label" })
hi("@tag",                  { fg = c.red })
hi("@tag.attribute",        { fg = c.yellow })
hi("@tag.delimiter",        { fg = c.br_black })
hi("@punctuation.bracket",  { fg = c.br_black })
hi("@punctuation.delimiter",{ fg = c.br_black })
hi("@punctuation.special",  { fg = c.cyan })
hi("@text",                 { fg = c.fg })
hi("@text.title",           { link = "Title" })
hi("@text.strong",          { bold = true })
hi("@text.emphasis",        { italic = true })
hi("@text.underline",       { underline = true })
hi("@text.strike",          { strikethrough = true })
hi("@text.uri",             { fg = c.cyan,    underline = true })
hi("@text.reference",       { fg = c.yellow })
hi("@text.todo",            { link = "Todo" })
hi("@text.warning",         { fg = c.yellow })
hi("@text.danger",          { fg = c.red })
hi("@text.diff.add",        { link = "DiffAdd" })
hi("@text.diff.delete",     { link = "DiffDelete" })

-- ── LSP ──────────────────────────────────────────────────────────────────────
hi("LspReferenceText",            {})
hi("LspReferenceRead",            {})
hi("LspReferenceWrite",           {})
hi("LspSignatureActiveParameter", { fg = c.yellow, bold = true })
hi("LspInlayHint",                { fg = c.br_black, italic = true })

-- ── Diagnostics ──────────────────────────────────────────────────────────────
hi("DiagnosticError",            { fg = c.red })
hi("DiagnosticWarn",             { fg = c.yellow })
hi("DiagnosticInfo",             { fg = c.cyan })
hi("DiagnosticHint",             { fg = c.green })
hi("DiagnosticOk",               { fg = c.green })
hi("DiagnosticUnderlineError",   { sp = c.red,    undercurl = true })
hi("DiagnosticUnderlineWarn",    { sp = c.yellow, undercurl = true })
hi("DiagnosticUnderlineInfo",    { sp = c.cyan,   undercurl = true })
hi("DiagnosticUnderlineHint",    { sp = c.green,  undercurl = true })
hi("DiagnosticVirtualTextError", { fg = c.red,    italic = true })
hi("DiagnosticVirtualTextWarn",  { fg = c.yellow, italic = true })
hi("DiagnosticVirtualTextInfo",  { fg = c.cyan,   italic = true })
hi("DiagnosticVirtualTextHint",  { fg = c.green,  italic = true })

-- ── Git (gitsigns / fugitive) ────────────────────────────────────────────────
hi("GitSignsAdd",    { fg = c.green })
hi("GitSignsChange", { fg = c.yellow })
hi("GitSignsDelete", { fg = c.red })

-- ── Telescope ────────────────────────────────────────────────────────────────
hi("TelescopeNormal",         { fg = c.fg,       bg = c.black })
hi("TelescopeBorder",         { fg = c.br_black, bg = c.black })
hi("TelescopePromptNormal",   { fg = c.fg,       bg = c.black })
hi("TelescopePromptBorder",   { fg = c.br_black, bg = c.black })
hi("TelescopePromptTitle",    { fg = c.bg,       bg = c.cyan })
hi("TelescopePreviewTitle",   { fg = c.bg,       bg = c.green })
hi("TelescopeResultsTitle",   { fg = c.bg,       bg = c.magenta })
hi("TelescopeSelection",      { fg = c.fg, bg = c.black })
hi("TelescopeMatching",       { fg = c.yellow,   bold = true })

-- ── nvim-tree ────────────────────────────────────────────────────────────────
hi("NvimTreeNormal",       { fg = c.fg,       bg = c.black })
hi("NvimTreeNormalNC",     { fg = c.fg,       bg = c.black })
hi("NvimTreeFolderName",   { fg = c.cyan })
hi("NvimTreeOpenedFolderName", { fg = c.cyan, bold = true })
hi("NvimTreeRootFolder",   { fg = c.magenta,  bold = true })
hi("NvimTreeSymlink",      { fg = c.yellow })
hi("NvimTreeExecFile",     { fg = c.green })
hi("NvimTreeGitNew",       { fg = c.green })
hi("NvimTreeGitDirty",     { fg = c.yellow })
hi("NvimTreeGitDeleted",   { fg = c.red })

-- ── which-key ────────────────────────────────────────────────────────────────
hi("WhichKey",          { fg = c.cyan })
hi("WhichKeyGroup",     { fg = c.yellow })
hi("WhichKeyDesc",      { fg = c.fg })
hi("WhichKeySeparator", { fg = c.br_black })
hi("WhichKeyFloat",     { bg = c.black })
